# Generated by Django 4.0.2 on 2022-02-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('created_at',)},
        ),
    ]
